### PR TITLE
DS-101: dark variant, split link, no divider.

### PR DESCRIPTION
**Pull request by jonearley**
## What's new?

- The logo now links to lib.umich.edu and the site name links to `/` or the provided site URL via prop.
- Removed the logo and website name divider: `/`.
- Added a dark blue background variant.
- Update documentation to include the dark variant as an example.
- Website name size reduced from large to medium and text is transformed to uppercase.

## Deploy preview

Screen Shot 2021-07-02 at 12 06 29 PM

Website Header — Design System — University of Michigan Library

### CODE REVIEW

**Review by respinos — APPROVED** [review]
All that's missing is analytics to know which variant gets used more :ducks:

**Review by bridgetburke — CHANGES_REQUESTED** [review]
On the doc site, the dark variant is showing up twice.
dark variant double

The small view site name isn't wrapping correctly.
Mobile variant

Should I update requirements in the ticket?

**Comment by jonearley** [comment]
> On the doc site, the dark variant is showing up twice.
> dark variant double
> 
> The small view site name isn't wrapping correctly.
> Mobile variant
> 
> Should I update the requirements in the ticket? I realize I didn't explicitly name out doc site things, like checking the codepen and different views.

The latest changes should address these concerns raised. Thanks for your review!

**Review by bridgetburke — APPROVED** [review]

**Review by respinos — APPROVED** [review]

**Comment by bridgetburke** [comment]
@jonearley- just a heads up that I noticed in VoiceOver that the MLibrary logo link reads as "Unlabelled image", then lib.umich.edu, then banner.

VoiceOver screenshot of text above

**Pull request merged**
