### PR TITLE
Responsive Table

### PR DESCRIPTION
**Pull request by erinesullivan**
# Overview
To add to the [HTML & CSS Workshop](http://localhost:8080/), we now have a responsive table! The design components are  also available on [Figma](https://www.figma.com/file/dxzvdBeoQTcBpSyMoLVQfY/?node-id=444%3A84).

## Setup
To apply the table styles, add the `.m-table` class directly to a `table` element.

### Responsive Breakpoints
There are two methods to make each `table.m-table` responsive:
1. Manually
2. Automatically

#### Manually
For a more universal layout change, there are three classes that can be added to each `table` trigger the responsive layout at specific breakpoints:
| Class                         | Size |
|-------------------------------|-----------|
| `.m-table--responsive-small`  | <= 720px     |
| `.m-table--responsive-medium` | <= 920px     |
| `.m-table--responsive-large`  | <= 1200px    |

These breakpoints were taken from the [Library's reusable media queries](https://github.com/mlibrary/lib.umich.edu/blob/master/src/reusable/media-queries.js).

#### Automatically
Optional JavaScript has been written to automatically make each `table.m-table` responsive at its smallest width. When the width of its parent is smaller than the width of the table, the `.m-table--responsive` class will be added to trigger the layout change. If the parent is not smaller, the class will be removed.

### Responsive Headers
In order for a header to appear in the responsive layout, the cell must have a `data-th` attribute. The value of the attribute should match the text in its associated `thead th` cell.

## Design Tokens
The `extrabold` font weight has been added as a design token, since it is used as the responsive heading, along with the footer.

## Testing
* Run `http://localhost:8080/`
* Check for accessibility
  * [ ] WAVE
  * [ ] ARC Toolkit
  * [ ] axe DevTools
* Check to see if its not broken in...
  * [ ] Chrome
  * [ ] Firefox
  * [ ] Safari
* Play around with it
  * What does it look like without row headers?
  * Remove the `.m-table--responsive-small` class and see the table become responsive on its own.
  * Add a different responsive class to see where the table breaks.
  * Add or change `data-th` attributes to see how it looks.

### CODE REVIEW

**Comment by respinos** [comment]
I think all my questions are with the javascript trigger: 

- are all `.m-table` tables re-flowable, or are some better left to scroll? (should there be a class/data that signals you want the JS to adapt the table?)
- if you _are_ expecting the JS, could that take care of populating `data-th` ?

**Comment by erinesullivan** [comment]
@respinos 

> * are all `.m-table` tables re-flowable, or are some better left to scroll? (should there be a class/data that signals you want the JS to adapt the table?)

If you add the JavaScript, it will apply to all `.m-table` tables. If we believe only specific tables should be responsive, we can figure out an approach for that.

> * if you _are_ expecting the JS, could that take care of populating `data-th` ?

It could. I did debate about writing JavaScript auto-populate the `data-th`. If these additions are important enough, I can continue working on it.

**Comment by jonearley** [comment]
When someone doesn't use `.m-table--responsive` could an alternative "responsive" class be provided such as:

```
.m-table-x-scroll-wrapper {
  overflow-x: scroll;
}
```

**Comment by jonearley** [comment]
Perhaps we could have an API to expose the responsiveness of tables via a data attribute? I find it tidy and open to future change easier if classes are only for styling.

## Default scroll along x

```html
<table class="m-table">
```

**Design notes**
- Can this be done without JavaScript? I think it might be, if I recall correctly. @erinesullivan found that adding `display: block;` to the table made it able to scroll along x.
- If JavaScript is available, can we add text note to be able to scroll along X and [follow the suggestions in this article](https://inclusive-components.design/data-tables/)?

## Optional single column rewrite via JavaScript

```html
<table class="m-table" data-responsive-variant="single-column">
```

**Design notes**
- This makes responsive variants open to more in the future, just in case.
- Makes the JavaScript target `tabl[data-responsive-variant="single-column]".
- The words used with the data attribute is open to renaming, but I feel confident in this approach.

**Comment by respinos** [comment]
I don't think you have to `display: block` the table to make it scroll.

**Pull request merged**
